# GitHub Actions workflow for Node.js backend CI/CD
name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ride_share
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend
      - name: Run backend tests
        run: npm test
        working-directory: ./backend
      - name: Run npm audit for vulnerabilities (backend)
        run: npm audit --audit-level=high
        working-directory: ./backend

      # Frontend
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      # Mobile
      - name: Install mobile dependencies
        run: npm install
        working-directory: ./mobile
      - name: Check mobile build (Expo)
        run: npx expo install && npx expo export --platform web
        working-directory: ./mobile

      # Deploy to Render: Render will auto-deploy from GitHub. No manual deploy step needed here.
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-test-results
          path: ./backend
